### ISSUE TITLE
doc review

### ISSUE THREAD

**Issue by briceburg** [dockerland/dex#37]
@Skrath would you mind giving the README.md and https://github.com/dockerland/dex/blob/master/docs/HOWTO.md#containerize-your-application  a lookover? Want to see if it's starting to make sense :)

**Comment by Skrath** [comment]
I really wish there was a built in system for simply commenting on already committed code.

**Comment by Skrath** [comment]
Made a small branch for this with some minor stuff. I didn't see anything in there that jumped out as needing to be overhauled or whatever.

Also, who broke the build?

**Comment by briceburg** [comment]
build has been fixed in fea1dad1f391aef411753ae03d58bbcc7a70c1e2  -- very touchy argparsing stuff, but I think it's nailed!
