### ISSUE TITLE
license police

### ISSUE THREAD

**Issue by briceburg** [dockerland/dex#5]
/cc @Skrath  -- GPLv9000 ?

**Comment by Skrath** [comment]
Ha, I wish that was a real version

**Comment by briceburg** [comment]
seriously -- what do you think about aligning w/ Docker proper (ASL)  -- https://github.com/docker/docker/blob/master/LICENSE ?
- It's not copyleft ( https://en.wikipedia.org/wiki/Apache_License#Licensing_conditions ) which kind of sucks but leads to corporate uptake 
- but it is GPL compatible -- and dex can be part of a larger GPL project.
