### ISSUE TITLE
Invalid Filter Label Error

### ISSUE THREAD

**Issue by twslade** [dockerland/dex#59]
```sh
$> docker -v
Docker version 1.13.0, build 49bf474
$> dex -v
Dex version v0.12.1-pr build fe46a4a
```

When running any Dex image I am getting the same error over and over. Specifically,
Error response from daemon: Invalid filter '"label'

After running bash -x, I have determined that the error is coming from

```sh
exec docker images -q --filter dangling=false --filter label=org.dockerland.dex.namespace=dex/v1 --filter label=org.dockerland.dex.image=sed '--filter="label=org.dockerland.dex.tag=latest"'
Error response from daemon: Invalid filter '"label'
```

I have since modified the dex binary located at ~/.badevops/bin/badevops-dex
I have removed the escaped quotations mark located on line 1703

```sh
# From
  [ -n "$tag" ] && flags+=( "--filter=\"label=org.dockerland.dex.tag=$tag\"" )
# To
  [ -n "$tag" ] && flags+=( "--filter=label=org.dockerland.dex.tag=$tag" )
```

Relevant commits:
b2b8755a
eceb6550

https://github.com/dockerland/dex/commit/b2b8755af3dcba63c3d73e0887ae80e73f89f7cb#diff-df569ecc394d345e5274ad4f4c551759L53
https://github.com/dockerland/dex/commit/eceb655010d71865f034d1405c3ddb8681097c7d#diff-0b400e09384611b5bd5e2efcb173ac92R47

**Comment by briceburg** [comment]
nice -- thanks @twslade 

I believe this was fixed in: https://github.com/dockerland/dex/commit/74b73aabe248f4f064d00a83965b0fdec74b3291

feel free to submit a PR for an issue like this next time
